FEDERATION_SERVER="https://foxcny.com/strbridge"
DEPOSIT_SERVER="https://foxcny.com/deposit"

ACCOUNTS=[
	"GAREELUB43IRHWEASCFBLKHURCGMHE5IF6XSE7EXDLACYHGRHM43RFOX",
	"GC76RMFNNXBFDSJRBXCABWLHXDK4ITVQSMI56DC2ZJVC3YOLLPCKKULT",
	"GBK4DFCUAZRNU7TJ4XUOJEADVQBLGVVVFKRTHHXNAXD7MTYUWR7HKCNY",
	"GCLDH6L6FBLTD3H3B23D6TIFVVTFBLZMNBC3ZOI6FGI5GPQROL4FOXIN",
	"GBTLWRHDUJNAKTQGH7YOQ6K56D6GKX2HSM2UF5A3RK7QAME25GFOXOUT"
]

[[CURRENCIES]]
code="CNY"
issuer="GAREELUB43IRHWEASCFBLKHURCGMHE5IF6XSE7EXDLACYHGRHM43RFOX"
image="https://ripplefox.com/images/ripplefox.png"

[[CURRENCIES]]
code="ULT"
issuer="GC76RMFNNXBFDSJRBXCABWLHXDK4ITVQSMI56DC2ZJVC3YOLLPCKKULT"
image="https://ripplefox.com/images/ult_100.png"